language:
- python
python:
- '3.4'
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: hP0Cbjf7tFjibQJBXPJldYbodyXSGaGxEi3AyggjND+oMkZoFYAli1I53SwP4Tvg1VhtHz/ega2yNxenc5Qf807DdodXx10hsPU8MLt1AFDS0jyp6a7bTqwpOZXoKRe9quZpDO6IZSBic7ifknSgAMCykNhuoVR2VKDv4qMJvLT3rYunWIoW9CoTEnbMturwKKsm52pT+ro7w/dQ//BjhxgSdQ6mwDV85Vy4REc7kSQ7/pcASEths/NZ8n2hPgDEbR/BEvUE0qmlVI9QWmGx66vmpG+32c0XNaRvUpEKh2+N3h4Eam+tbkxB4mRDlj9ap+sY0Xd20VLs066eN5ax0hsSWwhX7Wp67si5EgcipktOL4B0R9vURvO+eOSD3bSDv3uiiJa4/QrSYR/16lfrM7xi8fnDjyxM12KZBoqi1VqhgLQKHgkCxmMDBmJXb7NVzwvjmSRUPtBWgzNb9B9DI01RN7hlRQNqKxuHDEnmISszycZgl7z0BZaEOX7L6npXegKGGo+gNZ/FMqA4/C7fpZs684Nz0qIgKMsoF8TDonTTN6Soo1KJpR3oGTx4fug9/od8Egfa8NR6OtkG/SxSBMRsafNZnoROiaDRlX3LZpXofBWjcareYcImHHFySNsamefn3LBVZNrnrtKlWe7tH/oavwq0EnbcEkaaOgBUrzE=
  app: desolate-mesa-19936
  on:
    repo: powerlanguage/flasktaskr
